"""
Laser OS Tier 1 - Products/SKU Routes

This module handles all product/SKU-related routes.
"""

from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from app import db
from app.models import Product, ProjectProduct, Setting, ActivityLog
from app.services.activity_logger import log_activity
from datetime import datetime
from decimal import Decimal

bp = Blueprint('products', __name__, url_prefix='/products')


@bp.route('/')
def index():
    """
    List all products with optional filtering.
    
    Query Parameters:
        search: Search term for product name or SKU
        material: Filter by material
        page: Page number for pagination
    
    Returns:
        Rendered template with product list
    """
    # Get query parameters
    search = request.args.get('search', '').strip()
    material_filter = request.args.get('material', '').strip()
    page = request.args.get('page', 1, type=int)
    per_page = 50
    
    # Build query
    query = Product.query
    
    # Apply search filter
    if search:
        search_pattern = f'%{search}%'
        query = query.filter(
            db.or_(
                Product.name.like(search_pattern),
                Product.sku_code.like(search_pattern),
                Product.description.like(search_pattern)
            )
        )
    
    # Apply material filter
    if material_filter:
        query = query.filter(Product.material == material_filter)
    
    # Order by created date (newest first)
    query = query.order_by(Product.created_at.desc())
    
    # Paginate
    pagination = query.paginate(page=page, per_page=per_page, error_out=False)
    products = pagination.items
    
    # Get unique materials for filter dropdown
    materials_query = db.session.query(Product.material).distinct().filter(Product.material.isnot(None)).order_by(Product.material)
    materials = [m[0] for m in materials_query.all()]
    
    return render_template(
        'products/list.html',
        products=products,
        pagination=pagination,
        search=search,
        material_filter=material_filter,
        materials=materials
    )


@bp.route('/new', methods=['GET', 'POST'])
def new_product():
    """Create a new product."""
    if request.method == 'POST':
        try:
            # Get form data
            name = request.form.get('name', '').strip()
            description = request.form.get('description', '').strip()
            material = request.form.get('material', '').strip()
            thickness = request.form.get('thickness', '').strip()
            unit_price = request.form.get('unit_price', '').strip()
            notes = request.form.get('notes', '').strip()
            
            # Validate required fields
            if not name:
                flash('Product name is required', 'error')
                return redirect(url_for('products.new_product'))
            
            # Create product
            product = Product(
                name=name,
                description=description if description else None,
                material=material if material else None,
                thickness=Decimal(thickness) if thickness else None,
                unit_price=Decimal(unit_price) if unit_price else None,
                notes=notes if notes else None
            )
            
            # SKU code will be auto-generated by event listener
            
            db.session.add(product)
            db.session.commit()
            
            # Log activity
            log_activity(
                entity_type='PRODUCT',
                entity_id=product.id,
                action='CREATED',
                details=f'Created product: {product.name} ({product.sku_code})'
            )
            
            flash(f'Product "{product.name}" created successfully with SKU: {product.sku_code}', 'success')
            return redirect(url_for('products.detail', id=product.id))
            
        except Exception as e:
            db.session.rollback()
            flash(f'Error creating product: {str(e)}', 'error')
            return redirect(url_for('products.new_product'))
    
    # GET request - show form
    # Get default materials from settings
    materials_setting = Setting.query.filter_by(key='default_materials').first()
    materials = materials_setting.value.split(',') if materials_setting else []
    
    # Get default thicknesses from settings
    thicknesses_setting = Setting.query.filter_by(key='default_thicknesses').first()
    thicknesses = thicknesses_setting.value.split(',') if thicknesses_setting else []
    
    return render_template(
        'products/form.html',
        product=None,
        materials=materials,
        thicknesses=thicknesses
    )


@bp.route('/<int:id>')
def detail(id):
    """View product details."""
    product = Product.query.get_or_404(id)
    
    # Get projects using this product
    project_products = ProjectProduct.query.filter_by(product_id=id).all()
    
    # Get activity log
    activity_logs = ActivityLog.query.filter_by(
        entity_type='PRODUCT',
        entity_id=id
    ).order_by(ActivityLog.created_at.desc()).limit(20).all()
    
    return render_template(
        'products/detail.html',
        product=product,
        project_products=project_products,
        activity_logs=activity_logs
    )


@bp.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    """Edit a product."""
    product = Product.query.get_or_404(id)
    
    if request.method == 'POST':
        try:
            # Track changes for activity log
            changes = []
            
            # Get form data
            name = request.form.get('name', '').strip()
            description = request.form.get('description', '').strip()
            material = request.form.get('material', '').strip()
            thickness = request.form.get('thickness', '').strip()
            unit_price = request.form.get('unit_price', '').strip()
            notes = request.form.get('notes', '').strip()
            
            # Validate required fields
            if not name:
                flash('Product name is required', 'error')
                return redirect(url_for('products.edit', id=id))
            
            # Update fields and track changes
            if product.name != name:
                changes.append(f'name: "{product.name}" → "{name}"')
                product.name = name
            
            new_description = description if description else None
            if product.description != new_description:
                changes.append('description updated')
                product.description = new_description
            
            new_material = material if material else None
            if product.material != new_material:
                changes.append(f'material: "{product.material}" → "{new_material}"')
                product.material = new_material
            
            new_thickness = Decimal(thickness) if thickness else None
            if product.thickness != new_thickness:
                changes.append(f'thickness: {product.thickness} → {new_thickness}')
                product.thickness = new_thickness
            
            new_unit_price = Decimal(unit_price) if unit_price else None
            if product.unit_price != new_unit_price:
                changes.append(f'unit_price: {product.unit_price} → {new_unit_price}')
                product.unit_price = new_unit_price
            
            new_notes = notes if notes else None
            if product.notes != new_notes:
                changes.append('notes updated')
                product.notes = new_notes
            
            # Save changes
            if changes:
                db.session.commit()
                
                # Log activity
                log_activity(
                    entity_type='PRODUCT',
                    entity_id=product.id,
                    action='UPDATED',
                    details=f'Updated product: {", ".join(changes)}'
                )
                
                flash(f'Product "{product.name}" updated successfully', 'success')
            else:
                flash('No changes made', 'info')
            
            return redirect(url_for('products.detail', id=id))
            
        except Exception as e:
            db.session.rollback()
            flash(f'Error updating product: {str(e)}', 'error')
            return redirect(url_for('products.edit', id=id))
    
    # GET request - show form
    # Get default materials from settings
    materials_setting = Setting.query.filter_by(key='default_materials').first()
    materials = materials_setting.value.split(',') if materials_setting else []
    
    # Get default thicknesses from settings
    thicknesses_setting = Setting.query.filter_by(key='default_thicknesses').first()
    thicknesses = thicknesses_setting.value.split(',') if thicknesses_setting else []
    
    return render_template(
        'products/form.html',
        product=product,
        materials=materials,
        thicknesses=thicknesses
    )


@bp.route('/<int:id>/delete', methods=['POST'])
def delete(id):
    """Delete a product."""
    product = Product.query.get_or_404(id)
    
    try:
        # Check if product is used in any projects
        project_count = ProjectProduct.query.filter_by(product_id=id).count()
        
        if project_count > 0:
            flash(f'Cannot delete product "{product.name}" - it is used in {project_count} project(s)', 'error')
            return redirect(url_for('products.detail', id=id))
        
        # Log before deletion
        log_activity(
            entity_type='PRODUCT',
            entity_id=product.id,
            action='DELETED',
            details=f'Deleted product: {product.name} ({product.sku_code})'
        )
        
        product_name = product.name
        db.session.delete(product)
        db.session.commit()
        
        flash(f'Product "{product_name}" deleted successfully', 'success')
        return redirect(url_for('products.index'))
        
    except Exception as e:
        db.session.rollback()
        flash(f'Error deleting product: {str(e)}', 'error')
        return redirect(url_for('products.detail', id=id))

